import {
  UserProfile,
  TrackingPreferences,
  SleepScheduleConfig,
  Activity,
  RoutineItem,
  Subject,
  StudySession,
  WorkoutSession,
  Meal,
  WaterLog,
  SleepRecord,
  Habit,
  HabitLog,
  Goal,
  DailyReview,
  WeeklyReview,
  NotificationItem,
  JournalEntry,
} from '@/types/models';

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'usr_01',
  name: 'Alex Morgan',
  email: 'alex.morgan@daytrack.app',
  age: 26,
  height: 178,
  weight: 72,
  gender: 'Non-binary',
  timezone: 'America/New_York (EST)',
  avatarUrl: '',
  createdAt: '2026-01-10T08:00:00Z',
};

export const INITIAL_TRACKING_PREFERENCES: TrackingPreferences = {
  studies: true,
  coding: true,
  workout: true,
  sleep: true,
  meals: true,
  water: true,
  reading: true,
  meditation: true,
  hobbies: true,
  personalTasks: true,
  other: false,
};

export const INITIAL_SLEEP_CONFIG: SleepScheduleConfig = {
  targetBedtime: '23:00',
  targetWakeTime: '07:00',
  targetHours: 8,
};

const getTodayDateString = (): string => {
  return new Date().toISOString().split('T')[0];
};

const TODAY = getTodayDateString();

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act_01',
    title: 'Wake Up & Hydrate',
    category: 'sleep',
    priority: 'high',
    status: 'completed',
    startTime: '07:00',
    endTime: '07:30',
    date: TODAY,
    durationMinutes: 30,
    notes: 'Awake with natural sunlight, 500ml electrolyte water',
    completedAt: `${TODAY}T07:15:00Z`,
  },
  {
    id: 'act_02',
    title: 'Morning Upper Body Workout',
    category: 'workout',
    priority: 'high',
    status: 'completed',
    startTime: '07:30',
    endTime: '08:30',
    date: TODAY,
    durationMinutes: 60,
    notes: 'Push day: Bench press, overhead dumbbell press, incline flies',
    completedAt: `${TODAY}T08:28:00Z`,
  },
  {
    id: 'act_03',
    title: 'Nutritious Breakfast',
    category: 'meal',
    priority: 'medium',
    status: 'completed',
    startTime: '08:30',
    endTime: '09:00',
    date: TODAY,
    durationMinutes: 30,
    notes: 'Eggs, sourdough bread, sliced banana, warm matcha',
    completedAt: `${TODAY}T08:55:00Z`,
  },
  {
    id: 'act_04',
    title: 'College / Core Work Block',
    category: 'personal',
    priority: 'urgent',
    status: 'completed',
    startTime: '09:00',
    endTime: '13:00',
    date: TODAY,
    durationMinutes: 240,
    notes: 'Lectures and architecture design review',
    completedAt: `${TODAY}T13:00:00Z`,
  },
  {
    id: 'act_05',
    title: 'Deep Study: Distributed Algorithms',
    category: 'study',
    priority: 'high',
    status: 'completed',
    startTime: '14:00',
    endTime: '16:00',
    date: TODAY,
    durationMinutes: 120,
    notes: 'Consensus mechanisms, Raft logs, network partitions',
    completedAt: `${TODAY}T15:58:00Z`,
  },
  {
    id: 'act_06',
    title: 'Next.js Full Stack Engineering',
    category: 'coding',
    priority: 'high',
    status: 'pending',
    startTime: '17:00',
    endTime: '19:30',
    date: TODAY,
    durationMinutes: 150,
    notes: 'Component architecture, theme switcher and timeline animations',
  },
  {
    id: 'act_07',
    title: 'Wholesome Dinner & Hydration',
    category: 'meal',
    priority: 'medium',
    status: 'pending',
    startTime: '20:00',
    endTime: '21:00',
    date: TODAY,
    durationMinutes: 60,
    notes: 'Salmon, quinoa, roasted vegetables',
  },
  {
    id: 'act_08',
    title: 'Evening Non-Fiction Reading',
    category: 'reading',
    priority: 'low',
    status: 'pending',
    startTime: '22:30',
    endTime: '23:00',
    date: TODAY,
    durationMinutes: 30,
    notes: 'Designing Data-Intensive Applications (Chapter 6)',
  },
  {
    id: 'act_09',
    title: 'Wind-Down & Sleep',
    category: 'sleep',
    priority: 'urgent',
    status: 'pending',
    startTime: '23:00',
    endTime: '07:00',
    date: TODAY,
    durationMinutes: 480,
    notes: 'Aiming for consistent 8 hours restful recovery',
  },
];

export const INITIAL_ROUTINE_ITEMS: RoutineItem[] = [
  {
    id: 'rt_01',
    title: 'Wake Up & Morning Hydration',
    category: 'sleep',
    priority: 'high',
    startTime: '07:00',
    endTime: '07:30',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    repeatFrequency: 'daily',
    reminderMinutes: 0,
    notes: 'Drink 500ml water, stretch',
    active: true,
  },
  {
    id: 'rt_02',
    title: 'Gym & Functional Training',
    category: 'workout',
    priority: 'high',
    startTime: '07:30',
    endTime: '08:30',
    daysOfWeek: [1, 2, 4, 5, 6],
    repeatFrequency: 'weekly',
    reminderMinutes: 15,
    notes: 'Split training sessions',
    active: true,
  },
  {
    id: 'rt_03',
    title: 'Healthy Breakfast',
    category: 'meal',
    priority: 'medium',
    startTime: '08:30',
    endTime: '09:00',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    repeatFrequency: 'daily',
    active: true,
  },
  {
    id: 'rt_04',
    title: 'Academic & Professional Focus Block',
    category: 'personal',
    priority: 'urgent',
    startTime: '09:00',
    endTime: '13:00',
    daysOfWeek: [1, 2, 3, 4, 5],
    repeatFrequency: 'weekly',
    active: true,
  },
  {
    id: 'rt_05',
    title: 'Deep Study Session',
    category: 'study',
    priority: 'high',
    startTime: '14:00',
    endTime: '16:00',
    daysOfWeek: [1, 2, 3, 4, 5],
    repeatFrequency: 'weekly',
    reminderMinutes: 10,
    active: true,
  },
  {
    id: 'rt_06',
    title: 'Software Development & Creative Build',
    category: 'coding',
    priority: 'high',
    startTime: '17:00',
    endTime: '19:30',
    daysOfWeek: [1, 2, 3, 4, 5],
    repeatFrequency: 'weekly',
    active: true,
  },
  {
    id: 'rt_07',
    title: 'Mindful Dinner',
    category: 'meal',
    priority: 'medium',
    startTime: '20:00',
    endTime: '21:00',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    repeatFrequency: 'daily',
    active: true,
  },
  {
    id: 'rt_08',
    title: 'Quiet Reading & Screen Cut-off',
    category: 'reading',
    priority: 'low',
    startTime: '22:30',
    endTime: '23:00',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    repeatFrequency: 'daily',
    active: true,
  },
  {
    id: 'rt_09',
    title: 'Consistent Nightly Sleep',
    category: 'sleep',
    priority: 'urgent',
    startTime: '23:00',
    endTime: '07:00',
    daysOfWeek: [1, 2, 3, 4, 5, 6, 0],
    repeatFrequency: 'daily',
    active: true,
  },
];

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'sb_01',
    name: 'Distributed Systems & Cloud Architecture',
    targetHoursPerWeek: 14,
    color: '#38bdf8',
    priority: 'high',
  },
  {
    id: 'sb_02',
    name: 'Full Stack Engineering (Next.js & PostgreSQL)',
    targetHoursPerWeek: 12,
    color: '#818cf8',
    priority: 'urgent',
  },
  {
    id: 'sb_03',
    name: 'UI/UX Design Systems & Motion Design',
    targetHoursPerWeek: 8,
    color: '#34d399',
    priority: 'medium',
  },
];

export const INITIAL_STUDY_SESSIONS: StudySession[] = [
  {
    id: 'ss_01',
    subjectId: 'sb_01',
    subjectName: 'Distributed Systems & Cloud Architecture',
    topic: 'Raft consensus algorithm leader election',
    durationMinutes: 120,
    date: TODAY,
    focusRating: 5,
    notes: 'Understood heartbeat RPCs and election safety invariants',
  },
  {
    id: 'ss_02',
    subjectId: 'sb_02',
    subjectName: 'Full Stack Engineering (Next.js & PostgreSQL)',
    topic: 'Next.js App Router Server Actions & React Context',
    durationMinutes: 90,
    date: TODAY,
    focusRating: 4,
    notes: 'Optimized state transitions without layout shifts',
  },
  {
    id: 'ss_03',
    subjectId: 'sb_03',
    subjectName: 'UI/UX Design Systems & Motion Design',
    topic: 'Accessible high-contrast themes & smooth color blending',
    durationMinutes: 75,
    date: '2026-09-18',
    focusRating: 4,
    notes: 'Tuned slate palette variables for long readability',
  },
];

export const INITIAL_WORKOUT_SESSIONS: WorkoutSession[] = [
  {
    id: 'wo_01',
    title: 'Upper Body Push & Mobility',
    type: 'advanced',
    durationMinutes: 60,
    date: TODAY,
    completed: true,
    notes: 'Great energy, clean form on bench press',
    exercises: [
      {
        id: 'ex_01',
        name: 'Barbell Bench Press',
        sets: [
          { setNumber: 1, reps: 10, weightKg: 65, completed: true },
          { setNumber: 2, reps: 8, weightKg: 75, completed: true },
          { setNumber: 3, reps: 6, weightKg: 80, completed: true },
        ],
      },
      {
        id: 'ex_02',
        name: 'Incline Dumbbell Press',
        sets: [
          { setNumber: 1, reps: 12, weightKg: 24, completed: true },
          { setNumber: 2, reps: 10, weightKg: 26, completed: true },
          { setNumber: 3, reps: 8, weightKg: 28, completed: true },
        ],
      },
      {
        id: 'ex_03',
        name: 'Lateral Cable Raises',
        sets: [
          { setNumber: 1, reps: 15, weightKg: 9, completed: true },
          { setNumber: 2, reps: 12, weightKg: 10, completed: true },
        ],
      },
    ],
  },
  {
    id: 'wo_02',
    title: 'Posterior Chain Pull Session',
    type: 'simple',
    durationMinutes: 55,
    date: '2026-09-18',
    completed: true,
    notes: 'Deadlifts, pull-ups, face pulls',
  },
];

export const INITIAL_MEALS: Meal[] = [
  {
    id: 'ml_01',
    type: 'breakfast',
    time: '08:30',
    date: TODAY,
    foods: ['3 Scrambled Eggs', 'Sourdough Toast (2 slices)', 'Sliced Banana', 'Almond Butter', 'Green Tea'],
    notes: 'Clean whole foods breakfast with good protein balance',
  },
  {
    id: 'ml_02',
    type: 'lunch',
    time: '13:15',
    date: TODAY,
    foods: ['Grilled Chicken Breast (180g)', 'Wild Brown Rice', 'Steamed Broccoli & Zucchini', 'Olive Oil Drizzle'],
    notes: 'Light and sustaining before the study block',
  },
];

export const INITIAL_WATER_LOGS: WaterLog[] = [
  { id: 'wl_01', date: TODAY, amountMl: 500, time: '07:15' },
  { id: 'wl_02', date: TODAY, amountMl: 500, time: '10:30' },
  { id: 'wl_03', date: TODAY, amountMl: 750, time: '14:00' },
];

export const INITIAL_SLEEP_RECORDS: SleepRecord[] = [
  {
    id: 'sl_01',
    date: TODAY,
    bedtime: '23:10',
    wakeTime: '07:05',
    durationMinutes: 475, // 7h 55m
    quality: 4,
    notes: 'Fell asleep quickly; room was cool and dark',
  },
  {
    id: 'sl_02',
    date: '2026-09-18',
    bedtime: '23:05',
    wakeTime: '07:00',
    durationMinutes: 475,
    quality: 5,
    notes: 'Deep sleep, zero middle-of-the-night awakenings',
  },
  {
    id: 'sl_03',
    date: '2026-09-17',
    bedtime: '23:30',
    wakeTime: '07:15',
    durationMinutes: 465,
    quality: 4,
    notes: 'A bit later to bed due to finishing project milestone',
  },
  {
    id: 'sl_04',
    date: '2026-09-16',
    bedtime: '22:50',
    wakeTime: '06:55',
    durationMinutes: 485,
    quality: 5,
  },
];

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'hb_01',
    name: 'Daily Hydration (2.5L+)',
    category: 'water',
    currentStreak: 18,
    longestStreak: 25,
    frequency: 'daily',
    targetDays: [1, 2, 3, 4, 5, 6, 0],
    color: '#38bdf8',
    createdAt: '2026-01-01',
    completedToday: true,
  },
  {
    id: 'hb_02',
    name: 'Morning Workout & Stretch',
    category: 'workout',
    currentStreak: 6,
    longestStreak: 14,
    frequency: 'daily',
    targetDays: [1, 2, 3, 4, 5, 6],
    color: '#f97316',
    createdAt: '2026-01-01',
    completedToday: true,
  },
  {
    id: 'hb_03',
    name: 'Focused Coding Session',
    category: 'coding',
    currentStreak: 12,
    longestStreak: 20,
    frequency: 'daily',
    targetDays: [1, 2, 3, 4, 5],
    color: '#818cf8',
    createdAt: '2026-01-05',
    completedToday: false,
  },
  {
    id: 'hb_04',
    name: 'Evening Book Reading (20m)',
    category: 'reading',
    currentStreak: 9,
    longestStreak: 16,
    frequency: 'daily',
    targetDays: [1, 2, 3, 4, 5, 6, 0],
    color: '#a855f7',
    createdAt: '2026-01-10',
    completedToday: false,
  },
  {
    id: 'hb_05',
    name: 'Consistent Bedtime by 23:00',
    category: 'sleep',
    currentStreak: 7,
    longestStreak: 12,
    frequency: 'daily',
    targetDays: [1, 2, 3, 4, 5, 6, 0],
    color: '#06b6d4',
    createdAt: '2026-01-01',
    completedToday: false,
  },
  {
    id: 'hb_06',
    name: 'Mindful Meditation (10m)',
    category: 'personal',
    currentStreak: 14,
    longestStreak: 14,
    frequency: 'daily',
    targetDays: [1, 2, 3, 4, 5, 6, 0],
    color: '#10b981',
    createdAt: '2026-01-01',
    completedToday: true,
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'gl_01',
    title: 'Master Full Stack Cloud Architecture',
    description: 'Build enterprise-grade SaaS systems with Next.js, PostgreSQL, and scalable micro-services.',
    deadline: '2026-12-15',
    category: 'Coding & Career',
    progress: 72,
    milestones: [
      { id: 'm_01', title: 'HTML5 Semantic Layouts & CSS Design Systems', completed: true },
      { id: 'm_02', title: 'TypeScript Advanced Types & Generics', completed: true },
      { id: 'm_03', title: 'React 19 & Next.js App Router Architecture', completed: true },
      { id: 'm_04', title: 'Decoupled State & Dynamic Theme Engine', completed: true },
      { id: 'm_05', title: 'PostgreSQL Relational Schema & Prisma ORM', completed: false },
      { id: 'm_06', title: 'CI/CD Automated Deployment & Monitoring', completed: false },
    ],
  },
  {
    id: 'gl_02',
    title: 'Physical Vitality & Strength Milestone',
    description: 'Consistent strength training, 10,000 daily steps, and optimal mobility routines.',
    deadline: '2026-11-30',
    category: 'Fitness & Health',
    progress: 60,
    milestones: [
      { id: 'm_21', title: 'Maintain 5x weekly structured training for 8 weeks', completed: true },
      { id: 'm_22', title: 'Bodyweight bench press for clean 5 reps', completed: true },
      { id: 'm_23', title: 'Consistent 7.5+ hours average weekly sleep', completed: true },
      { id: 'm_24', title: 'Sub-25 minute 5K road run', completed: false },
    ],
  },
  {
    id: 'gl_03',
    title: 'Read 20 Technical & Philosophical Books',
    description: 'Broaden perspective across systems thinking, cognitive psychology, and technology history.',
    deadline: '2026-12-31',
    category: 'Self-Improvement',
    progress: 55,
    milestones: [
      { id: 'm_31', title: 'Read Designing Data-Intensive Applications', completed: true },
      { id: 'm_32', title: 'Read Atomic Habits & Deep Work', completed: true },
      { id: 'm_33', title: 'Read Thinking in Systems by Donella Meadows', completed: false },
      { id: 'm_34', title: 'Read Structure and Interpretation of Computer Programs', completed: false },
    ],
  },
];

export const INITIAL_DAILY_REVIEWS: DailyReview[] = [
  {
    id: 'dr_01',
    date: '2026-09-18',
    mood: 5,
    energy: 4,
    stress: 2,
    wentWell: 'Maintained unbroken focus during the 2-hour algorithm deep dive; workouts felt strong.',
    couldImprove: 'Spent 15 extra minutes browsing social media before dinner.',
    tomorrowFocus: 'Ship the Next.js theme switcher and start the Weekly Review summary component.',
  },
  {
    id: 'dr_02',
    date: '2026-09-17',
    mood: 4,
    energy: 4,
    stress: 3,
    wentWell: 'Hydration goal surpassed early, good pacing across morning tasks.',
    couldImprove: 'Went to bed 30 minutes later than planned schedule.',
    tomorrowFocus: 'Stick rigidly to 23:00 screen shut-off.',
  },
];

export const INITIAL_WEEKLY_REVIEW: WeeklyReview = {
  id: 'wr_01',
  weekStartDate: '2026-09-14',
  weekEndDate: '2026-09-20',
  completedActivities: 47,
  plannedActivities: 54,
  studyMinutes: 875, // 14h 35m
  workoutMinutes: 310, // 5h 10m
  avgSleepMinutes: 448, // 7h 28m
  waterLoggedMl: 17500, // 17.5L
  routineConsistencyPct: 87,
  achievements: [
    'Completed 47 of 54 scheduled routine activities (87% adherence).',
    'Recorded 14 hours and 35 minutes of deep study across 3 core subjects.',
    'Completed 5 dedicated workout sessions with progressive overload recorded.',
    'Maintained average sleep of 7h 28m across all recorded nights.',
    'Unbroken 18-day hydration streak.',
  ],
  observations: [
    'Deep focus blocks scheduled between 14:00 and 16:00 have the highest completion rate (95%).',
    'Evening reading consistency is slightly lower on Thursday and Friday nights.',
    'Workout sessions completed in the morning (07:30) correlate with higher afternoon energy ratings.',
  ],
  focusAreas: [
    'Keep evening winding-down routine consistent at 22:30 without screen intrusion.',
    'Schedule a 10-minute buffer after the college block to prevent afternoon fatigue.',
  ],
  nextWeekRecommendations: [
    'Maintain the 07:00 wake-up routine on weekends to preserve circadian rhythm.',
    'Add an active recovery stretch session on Wednesday afternoon.',
  ],
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'Hydration Milestone',
    message: "You're at 1.75L / 2.5L today. One more glass hits your daily target!",
    time: '14:05',
    read: false,
    type: 'achievement',
  },
  {
    id: 'notif_02',
    title: 'Upcoming: Next.js Engineering',
    message: 'Scheduled to begin at 17:00. Focus Timer is ready.',
    time: '16:45',
    read: false,
    type: 'reminder',
  },
  {
    id: 'notif_03',
    title: 'Weekly Analysis Ready',
    message: 'Your automatic weekly review with 87% routine consistency is available.',
    time: 'Yesterday',
    read: true,
    type: 'info',
  },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'j_01',
    date: TODAY,
    title: 'Consistency vs Peak Intensity',
    content: 'Observing that the days where I protect the routine blocks (wake up, gym, deep work) produce far more sustained clarity than intense burst sessions that lead to burnout. The slate medium mode in DayTrack has been exceptionally restful on my eyes during long sessions.',
    tags: ['Productivity', 'Mindset', 'Routine'],
  },
  {
    id: 'j_02',
    date: '2026-09-17',
    title: 'Rethinking Evening Recovery',
    content: 'Cutting screen exposure at 22:30 was transformative for sleep quality. Measured a full 7h 55m restful recovery with zero night awakenings.',
    tags: ['Sleep', 'Wellness'],
  },
];
